### ISSUE TITLE
🐛 Using a third-party database as a session storage leads to panic

### ISSUE THREAD

**Issue by hugmouse** [gofiber/fiber#1046]
**Fiber version**
`Fiber v2.2.2`

**Issue description**

If you use a third-party database (like sqlite3/postgres) to store session info and then try to get a value that does not exist there, a panic occurs. 

A third-party database may be Sqlite3 or Postgres, this error may also occur with other databases, but I was not able to check.

By the way, if you use the standard config, which contains information about the session just in memory - then such a panic does not happen.

Related packages: 

- https://github.com/gofiber/storage/tree/main/sqlite3
- https://github.com/gofiber/storage/tree/main/postgres

**Code snippet** (with panic)

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
	"github.com/gofiber/storage/sqlite3"
)

func main() {
	app := fiber.New()

	store := session.New(session.Config{Storage: sqlite3.New()})

	app.Get("/get", func(c *fiber.Ctx) error {
		sess, err := store.Get(c) // panics
		if err != nil {
			return c.SendString(err.Error())
		}

		sess.Get("bang")

		return c.SendString("So anyway, i started blasting")
	})

	app.Listen(":3000")
}
```

**Code snippet** (without panic)

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
)

func main() {
	app := fiber.New()

	store := session.New()

	app.Get("/get", func(c *fiber.Ctx) error {
		sess, err := store.Get(c)
		if err != nil {
			return c.SendString(err.Error())
		}

		sess.Get("bang")

		return c.SendString("So anyway, i started blasting")
	})

	app.Listen(":3000")
}
```

**Panic**

`panic: runtime error: index out of range [0] with length 0`

**Log**

```
goroutine 34 [running]:
github.com/gofiber/fiber/v2/internal/gotiny.(*Decoder).decBool(...)
        /Users/mysh/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.2/internal/gotiny/decbase.go:11
github.com/gofiber/fiber/v2/internal/gotiny.(*Decoder).decIsNotNil(...)
        /Users/mysh/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.2/internal/gotiny/decbase.go:121
github.com/gofiber/fiber/v2/internal/gotiny.buildDecEngine.func1(0xc00009c0f0, 0xc0000a6088)
        /Users/mysh/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.2/internal/gotiny/decEngine.go:95 +0x1bf
github.com/gofiber/fiber/v2/internal/gotiny.(*Decoder).Decode(0xc00009c0f0, 0x0, 0x0, 0x0, 0xc000297ad8, 0x1, 0x1, 0xc0000ae0f8)
        /Users/mysh/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.2/internal/gotiny/decoder.go:75 +0x92
github.com/gofiber/fiber/v2/internal/gotiny.Unmarshal(0x0, 0x0, 0x0, 0xc000297ad8, 0x1, 0x1, 0x0)
        /Users/mysh/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.2/internal/gotiny/decoder.go:19 +0x8f
github.com/gofiber/fiber/v2/middleware/session.(*Store).Get(0xc0002941c0, 0xc0000b8000, 0xc0000ae060, 0xc0001c8840, 0x8)
        /Users/mysh/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.2/middleware/session/store.go:58 +0x26c
main.main.func1(0xc0000b8000, 0xc0000ae060, 0x4)
        /Users/mysh/go/src/fiberStruct/main.go:16 +0x38
github.com/gofiber/fiber/v2.(*App).next(0xc0001acd80, 0xc0000b8000, 0xc0000b8000, 0x34169458, 0x3416945800000002)
        /Users/mysh/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.2/router.go:126 +0x1b9
github.com/gofiber/fiber/v2.(*App).handler(0xc0001acd80, 0xc0000aa000)
        /Users/mysh/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.2/router.go:154 +0x11a
github.com/valyala/fasthttp.(*Server).serveConn(0xc0001af200, 0x46dea20, 0xc00009e008, 0x0, 0x0)
        /Users/mysh/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/server.go:2168 +0x11ac
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0001a8c80, 0xc00009a040)
        /Users/mysh/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/workerpool.go:223 +0xc2
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0001a8c80, 0xc00009a040, 0x45a8ac0, 0xc00009a040)
        /Users/mysh/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /Users/mysh/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/workerpool.go:194 +0x115
exit status 2
```

Or more readable with `panicparse`: 

```
1: running [Created by fasthttp.(*workerPool).getCh @ workerpool.go:194]
    gotiny   decbase.go:11     (*Decoder).decBool(...)
    gotiny   decbase.go:121    (*Decoder).decIsNotNil(...)
    gotiny   decEngine.go:95   buildDecEngine.func1(Type(#2))
    gotiny   decoder.go:75     (*Decoder).Decode(*Decoder(#2), []byte(0x0 len=0 cap=0), interface{}(#7), interface{}(0x1))
    gotiny   decoder.go:19     Unmarshal([]byte(0x0 len=0 cap=0), interface{}(#7), interface{}(0x1))
    session  store.go:58       (*Store).Get(*Store(0xc0002941c0), *Ctx(#4), #3, 0xc0001c8840, 0x8)
    main     main.go:16        main.func1(#4, #3, 0x4)
    v2       router.go:126     (*App).next(*App(#6), *Ctx(#4), #4, 0x34169458, 0x3416945800000002)
    v2       router.go:154     (*App).handler(*App(#6), *RequestCtx(0xc0000aa000))
    fasthttp server.go:2168    (*Server).serveConn(*Server(0xc0001af200), Conn(0x46dea20), 0x0, 0x0)
    fasthttp workerpool.go:223 (*workerPool).workerFunc(*workerPool(#5), *workerChan(#1))
    fasthttp workerpool.go:195 (*workerPool).getCh.func1(*workerPool(#5), #1, 0x45a8ac0, #1)
exit status 2
```

**Comment by hugmouse** [comment]
Also in one of my projects now has a `panic: unknown typ:bool`, but so far I have not been able to achieve stable reproduction of this error lol

**Comment by Fenny** [comment]
Your database could be corrupt or have incorrect values, could you try to reset it by doing the following:
```go
store := session.New(session.Config{
  Storage: sqlite3.New(sqlite3.Config{
     Reset: true,
  })
})
```

**Comment by hugmouse** [comment]
> Your database could be corrupt or have incorrect values, could you try to reset it by doing the following:
> 
> ```go
> store := session.New(session.Config{
>   Storage: sqlite3.New(sqlite3.Config{
>      Reset: true,
>   })
> })
> ```

Unfortunately, it didn't change anything. Same error. I even recorded a small video demo, heh

[fiber.mp4.zip](https://github.com/gofiber/fiber/files/5626126/fiber.mp4.zip)

**logs**

```
panic: runtime error: index out of range [0] with length 0


To see all goroutines, visit https://github.com/maruel/panicparse#gotraceback

1: running [Created by fasthttp.(*workerPool).getCh @ workerpool.go:194]
    gotiny   decbase.go:11     (*Decoder).decBool(...)
    gotiny   decbase.go:121    (*Decoder).decIsNotNil(...)
    gotiny   decEngine.go:95   buildDecEngine.func1(Type(#2))
    gotiny   decoder.go:75     (*Decoder).Decode(*Decoder(#2), []byte(0x0 len=0 cap=0), interface{}(#7), interface{}(0x1))
    gotiny   decoder.go:19     Unmarshal([]byte(0x0 len=0 cap=0), interface{}(#7), interface{}(0x1))
    session  store.go:58       (*Store).Get(*Store(0xc00017c230), *Ctx(#4), #3, 0xc0001349a0, 0x8)
    main     main.go:19        main.func1(#4, #3, 0x4)
    v2       router.go:126     (*App).next(*App(#6), *Ctx(#4), #4, 0x35dfcf20, 0x35dfcf2000000002)
    v2       router.go:154     (*App).handler(*App(#6), *RequestCtx(0xc0000a2000))
    fasthttp server.go:2168    (*Server).serveConn(*Server(0xc000123200), Conn(0x46de8e0), 0x0, 0x0)
    fasthttp workerpool.go:223 (*workerPool).workerFunc(*workerPool(#5), *workerChan(#1))
    fasthttp workerpool.go:195 (*workerPool).getCh.func1(*workerPool(#5), #1, 0x45a8780, #1)
exit status 2
```

**Comment by Fenny** [comment]
@hugmouse could you try again with `v2.2.3`?

**Comment by hugmouse** [comment]
> @hugmouse could you try again with `v2.2.3`?

Tested `v2.2.3` with Postgres and Sqlite3 - this panic no longer present. Thank you!
