### ISSUE TITLE
How should I pass my store to my handlers🤗 

### ISSUE THREAD

**Issue by michael-ottink** [gofiber/fiber#1103]
**Question description**
I am making a new store in my main function and then I pass it to all my handlers but when I make a request to that endpoint the middleware throws an error

**Code snippet** _Optional_

```go
 func main() {
	err := godotenv.Load()

	if err != nil {
		panic(err)
	}

	databaseDriver, errDriver := envKit.GetEnvStr("DB_DRIVER")
	databaseHost, errHost := envKit.GetEnvStr("DB_HOST")
	databaseUser, errUser := envKit.GetEnvStr("DB_USER")
	databasePassword, errPassword := envKit.GetEnvStr("DB_PASS")
	databasePort, errPort := envKit.GetEnvInt("DB_PORT")
	databaseName, errName := envKit.GetEnvStr("DB_NAME")
	databaseTimezone, errTimezone := envKit.GetEnvStr("DB_TIMEZONE")
	appPort, errAppPort := envKit.GetEnvStr("APP_PORT")
	err = multierr.Combine(errDriver, errHost, errUser, errPassword, errPort, errName, errTimezone, errAppPort)

	if err != nil {
		panic(err)
	}

	config := database.Config{
		Driver:   databaseDriver,
		Host:     databaseHost,
		Username: databaseUser,
		Password: databasePassword,
		Port:     databasePort,
		Database: databaseName,
		Timezone: databaseTimezone,
	}

	db, err := database.NewPostgres(&config)
	migrate(db)

	if err != nil || db == nil {
		panic(err)
	}

	app := fiber.New()
	// app.Use(logger.New())
	app.Use(cors.New())

	storage := postgres.New(postgres.Config{
		Host:       databaseHost,
		Port:       databasePort,
		Username:   databaseUser,
		Password:   databasePassword,
		Database:   databaseName,
		Table:      "fiber_storage",
		Reset:      false,
		GCInterval: 10 * time.Second,
	})
	store := session.New(session.Config{
		Storage: storage,
	})

	SetupAPIV1Routes(app, db, store)
	printRouteTable(app.Stack())

	log.Fatal(app.Listen(":" + appPort))
}

func SetupAPIV1Routes(app *fiber.App, db *database.Database, store *session.Store) {

	crm := app.Group("/api/v1/crm", middleware.AuthenticationRequired(store))

	company := crm.Group("/company")
	company.Get("/", handler.Companies(db))
}

package middleware

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
)

func AuthenticationRequired(store *session.Store) func(c *fiber.Ctx) error {
	return func(c *fiber.Ctx) error {

		session, err := store.Get(c)

		if err != nil {
			return c.SendString("session not found")
		}

		user := session.Get("user")

		if user == nil {
			return c.SendString("authentication error")
		}

		return c.Next()
	}
}

```
But I get the following error when making a request to that endpoint

```
goroutine 13 [running]:
reflect.New(0x0, 0x0, 0x16, 0x1154a20, 0xc0002a4190)
        c:/go/src/reflect/value.go:2372 +0xc9
github.com/gofiber/fiber/v2/internal/gotiny.buildDecEngine.func7(0xc0004d4140, 0xc0002a4190)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/internal/gotiny/decEngine.go:188 +0x289
github.com/gofiber/fiber/v2/internal/gotiny.buildDecEngine.func4(0xc0004d4140, 0xc000486718)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/internal/gotiny/decEngine.go:154 +0x25c
github.com/gofiber/fiber/v2/internal/gotiny.buildDecEngine.func6(0xc0004d4140, 0xc000486700)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/internal/gotiny/decEngine.go:172 +0x55
github.com/gofiber/fiber/v2/internal/gotiny.buildDecEngine.func1(0xc0004d4140, 0xc000406da8)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/internal/gotiny/decEngine.go:100 +0xa8
github.com/gofiber/fiber/v2/internal/gotiny.(*Decoder).Decode(0xc0004d4140, 0xc0000c4720, 0x5a, 0x60, 0xc0005678e0, 0x1, 0x1, 0xc0005011c0)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/internal/gotiny/decoder.go:75 +0x98
github.com/gofiber/fiber/v2/internal/gotiny.Unmarshal(0xc0000c4720, 0x5a, 0x60, 0xc0005678e0, 0x1, 0x1, 0x0)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/internal/gotiny/decoder.go:19 +0x94
github.com/gofiber/fiber/v2/middleware/session.(*Store).Get(0xc00033c0e0, 0xc00055e280, 0x1b, 0xc0003ea840, 0x1)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/middleware/session/store.go:62 +0x20b
github.com/username/project-name/app/middleware.AuthenticationRequired.func1(0xc00055e280, 0xc0000a31a0, 0x13)
        D:/werk/project-name/server/app/middleware/authentication.go:11 +0x3f
github.com/gofiber/fiber/v2.(*App).next(0xc000386000, 0xc00055e280, 0x1b, 0x120ca21, 0x1)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/router.go:126 +0x1c2
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc00055e280, 0x121e9b6, 0x1b)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/ctx.go:632 +0x92
github.com/gofiber/fiber/v2/middleware/cors.New.func1(0xc00055e280, 0xc0000a31a0, 0x13)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/middleware/cors/cors.go:141 +0x316
github.com/gofiber/fiber/v2.(*App).next(0xc000386000, 0xc00055e280, 0xc00055e280, 0x5, 0x8)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/router.go:126 +0x1c2
github.com/gofiber/fiber/v2.(*App).handler(0xc000386000, 0xc00046cf00)
        C:/Users/username/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.4/router.go:154 +0x125
github.com/valyala/fasthttp.(*Server).serveConn(0xc000134d80, 0x12ffbe0, 0xc000606020, 0x0, 0x0)
        C:/Users/username/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/server.go:2168 +0x11ac
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0003fe1e0, 0xc000446760)
        C:/Users/username/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/workerpool.go:223 +0xcd
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0003fe1e0, 0xc000446760, 0x1123d60, 0xc000446760)
        C:/Users/username/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/workerpool.go:195 +0x3c
created by github.com/valyala/fasthttp.(*workerPool).getCh
        C:/Users/username/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/workerpool.go:194 +0x115
```

**Comment by michael-ottink** [comment]
Got the answer from the discord server

```
store := session.New(...)
store.RegisterType(&UserSession{})
```
