### ISSUE TITLE
🐛 runtime: out of memory

### ISSUE THREAD

**Issue by z-ab** [gofiber/fiber#1579]
go version 1.17
fiber 2.20

# github.com/gofiber/fiber/v2/internal/go-json/encoder/vm
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0xcf51e2, 0x6800000})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sysMap(0xc021800000, 0x429960, 0x7ffc82a6ceb8)
	/usr/local/go/src/runtime/mem_linux.go:169 +0x96
runtime.(*mheap).grow(0x1387460, 0x3289)
	/usr/local/go/src/runtime/mheap.go:1393 +0x225
runtime.(*mheap).allocSpan(0x1387460, 0x3289, 0x0, 0x1)
	/usr/local/go/src/runtime/mheap.go:1179 +0x165
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:913 +0x69
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:383 +0x49

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:350 fp=0xc001a870c8 sp=0xc001a870c0 pc=0x464f00
runtime.(*mheap).alloc(0x6512000, 0x3289, 0x0, 0x0)
	/usr/local/go/src/runtime/mheap.go:907 +0x73 fp=0xc001a87118 sp=0xc001a870c8 pc=0x425c93
runtime.(*mcache).allocLarge(0x7f64f8c3a108, 0x6512000, 0xd0, 0x1)
	/usr/local/go/src/runtime/mcache.go:227 +0x89 fp=0xc001a87178 sp=0xc001a87118 pc=0x416909
runtime.mallocgc(0x6512000, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:1082 +0x5c5 fp=0xc001a871f8 sp=0xc001a87178 pc=0x40ccc5
runtime.growslice(0xc001459660, {0xc01ab1c000, 0x0, 0x0}, 0x1f1e)
	/usr/local/go/src/runtime/slice.go:261 +0x4ac fp=0xc001a87260 sp=0xc001a871f8 pc=0x44ca8c
cmd/compile/internal/ssa.(*debugState).appendLiveSlot(...)
	/usr/local/go/src/cmd/compile/internal/ssa/debug.go:301
cmd/compile/internal/ssa.(*debugState).liveness(0xc001459660)
	/usr/local/go/src/cmd/compile/internal/ssa/debug.go:737 +0xa3b fp=0xc001a87448 sp=0xc001a87260 pc=0x72d23b
cmd/compile/internal/ssa.BuildFuncDebug(0xc6f200, 0xc000702700, 0x50, 0x39)
	/usr/local/go/src/cmd/compile/internal/ssa/debug.go:661 +0xa0c fp=0xc001a875f0 sp=0xc001a87448 pc=0x72c18c
cmd/compile/internal/ssagen.genssa(0xc000702700, 0xc002d89d50)
	/usr/local/go/src/cmd/compile/internal/ssagen/ssa.go:6983 +0xc37 fp=0xc001a87ad0 sp=0xc001a875f0 pc=0xa83f57
cmd/compile/internal/ssagen.Compile(0xc00055b760, 0xc0012c01a0)
	/usr/local/go/src/cmd/compile/internal/ssagen/pgen.go:175 +0x266 fp=0xc001a87b98 sp=0xc001a87ad0 pc=0xa4be06
cmd/compile/internal/gc.compileFunctions.func4.1(0x1)
	/usr/local/go/src/cmd/compile/internal/gc/compile.go:153 +0x3a fp=0xc001a87bd8 sp=0xc001a87b98 pc=0xc02aba
cmd/compile/internal/gc.compileFunctions.func2(0x0)
	/usr/local/go/src/cmd/compile/internal/gc/compile.go:125 +0x1e fp=0xc001a87bf0 sp=0xc001a87bd8 pc=0xc071be
cmd/compile/internal/gc.compileFunctions.func4({0xc0013e6400, 0x28, 0x40})
	/usr/local/go/src/cmd/compile/internal/gc/compile.go:152 +0x53 fp=0xc001a87c38 sp=0xc001a87bf0 pc=0xc029b3
cmd/compile/internal/gc.compileFunctions()
	/usr/local/go/src/cmd/compile/internal/gc/compile.go:163 +0x162 fp=0xc001a87c98 sp=0xc001a87c38 pc=0xc02882
cmd/compile/internal/gc.Main(0xd16478)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:287 +0xf3a fp=0xc001a87f20 sp=0xc001a87c98 pc=0xc049da
main.main()
	/usr/local/go/src/cmd/compile/main.go:55 +0xdd fp=0xc001a87f80 sp=0xc001a87f20 pc=0xc26f3d
runtime.main()
	/usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc001a87fe0 sp=0xc001a87f80 pc=0x437a07
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc001a87fe8 sp=0xc001a87fe0 pc=0x466fe1

**Comment by liaohongxing** [comment]
question info ?

**Comment by dn-l** [comment]
Got same error:
```
# github.com/gofiber/fiber/v2/internal/go-json/encoder/vm
fatal error: runtime: out of memory
```

**Comment by hi019** [comment]
@dn-l Hey. You should create a new issue for the error so that it's easier to track

**Comment by dn-l** [comment]
I will! As soon as I figure out why it's happening
