### ISSUE TITLE
🤗 Retrieve app stack trace in error handling middleware

### ISSUE THREAD

**Issue by ericreis** [gofiber/fiber#1845]
**Question description**
Hello, I'm having trouble trying to retrieve my application's stacktrace, but when calling the `debug.Stack()` method it seems that the context has already changed and the stacktrace doesn't show the location where my application panicked or raised an error:

```
goroutine 167 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/Users/ericreis/.goenv/versions/1.15.15/src/runtime/debug/stack.go:24 +0xa5
github.com/vtex/price-computing/api/middlewares.HandleHTTPRequestError(0xc018a73600, 0x0, 0x0)
	/Users/ericreis/dev/vtex/price-computing/api/middlewares/error_handling.go:92 +0x1148
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc018a73600, 0x0, 0x0)
	/Users/ericreis/go/1.18.0/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/ctx.go:706 +0xac
github.com/gofiber/fiber/v2/middleware/recover.New.func1(0xc018a73600, 0x0, 0x0)
	/Users/ericreis/go/1.18.0/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/middleware/recover/recover.go:45 +0x189
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc018a73600, 0x0, 0x0)
	/Users/ericreis/go/1.18.0/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/ctx.go:706 +0xac
github.com/vtex/price-computing/api/middlewares.HTTPRequestLatency(0xc018a73600, 0x0, 0x0)
	/Users/ericreis/dev/vtex/price-computing/api/middlewares/latency.go:48 +0x76
github.com/gofiber/fiber/v2.(*App).next(0xc0005461a0, 0xc018a73600, 0xc018a73601, 0x0, 0x0)
	/Users/ericreis/go/1.18.0/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/router.go:127 +0x362
github.com/gofiber/fiber/v2.(*App).handler(0xc0005461a0, 0xc0197fa000)
	/Users/ericreis/go/1.18.0/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/router.go:155 +0xd6
github.com/valyala/fasthttp.(*Server).serveConn(0xc000548000, 0x21cd2e0, 0xc019562dc0, 0x0, 0x0)
	/Users/ericreis/go/1.18.0/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251 +0x10cc
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00059e000, 0xc0197f6840)
	/Users/ericreis/go/1.18.0/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223 +0xfd
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc00059e000, 0xc0197f6840, 0x1ee3e80, 0xc0197f6840)
	/Users/ericreis/go/1.18.0/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/Users/ericreis/go/1.18.0/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:194 +0x1cd
```

I tried using the `StackTraceHandler` feature to correctly retrieve it and the stacktrace there looks good:

```
goroutine 119 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/Users/ericreis/.goenv/versions/1.15.15/src/runtime/debug/stack.go:24 +0xa5
github.com/vtex/price-computing/api/middlewares.StackTraceHandler(0x1f093c0, 0x2199a30)
	/Users/ericreis/dev/vtex/price-computing/api/middlewares/recover.go:11 +0x34
github.com/gofiber/fiber/v2/middleware/recover.New.func1.1(0x0, 0x1, 0x20cbbd8, 0xc01c56b6f8)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/middleware/recover/recover.go:33 +0x8a
panic(0x1f093c0, 0x2199a30)
	/Users/ericreis/.goenv/versions/1.15.15/src/runtime/panic.go:975 +0x4c6
github.com/vtex/price-computing/routes.(*Routes).ComputePrice(0xc0004e9540, 0xc01c1fadc0, 0x0, 0x0)
	/Users/ericreis/dev/vtex/price-computing/routes/compute.go:35 +0x45
github.com/gofiber/fiber/v2.(*App).next(0xc0003f7a00, 0xc01c1fadc0, 0x21cfb01, 0x0, 0x0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/router.go:127 +0x362
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc01c1fadc0, 0x0, 0x0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/ctx.go:709 +0xf6
github.com/vtex/price-computing/api/middlewares.Auth(0xc01c1fadc0, 0x0, 0x0)
	/Users/ericreis/dev/vtex/price-computing/api/middlewares/auth.go:113 +0x53d
github.com/gofiber/fiber/v2.(*App).next(0xc0003f7a00, 0xc01c1fadc0, 0xffffffffffffff01, 0x0, 0x0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/router.go:127 +0x362
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc01c1fadc0, 0x0, 0x0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/ctx.go:709 +0xf6
github.com/vtex/price-computing/api/middlewares.HandleHTTPRequestError(0xc01c1fadc0, 0x0, 0x0)
	/Users/ericreis/dev/vtex/price-computing/api/middlewares/error_handling.go:22 +0x4e
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc01c1fadc0, 0x0, 0x0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/ctx.go:706 +0xac
github.com/vtex/price-computing/api/middlewares.HTTPRequestLatency(0xc01c1fadc0, 0x0, 0x0)
	/Users/ericreis/dev/vtex/price-computing/api/middlewares/latency.go:48 +0x76
github.com/gofiber/fiber/v2.(*App).next(0xc0003f7a00, 0xc01c1fadc0, 0x1, 0x0, 0x0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/router.go:127 +0x362
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc01c1fadc0, 0x0, 0x0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/ctx.go:709 +0xf6
github.com/gofiber/fiber/v2/middleware/recover.New.func1(0xc01c1fadc0, 0x0, 0x0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/middleware/recover/recover.go:45 +0x189
github.com/gofiber/fiber/v2.(*App).next(0xc0003f7a00, 0xc01c1fadc0, 0xc01c1fad01, 0x0, 0x0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/router.go:127 +0x362
github.com/gofiber/fiber/v2.(*App).handler(0xc0003f7a00, 0xc01c352000)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/gofiber/fiber/v2@v2.18.0/router.go:155 +0xd6
github.com/valyala/fasthttp.(*Server).serveConn(0xc018c30000, 0x21cd800, 0xc0005958c0, 0x0, 0x0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251 +0x10cc
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000143360, 0xc01c34a8e0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223 +0xfd
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc000143360, 0xc01c34a8e0, 0x1ee4240, 0xc01c34a8e0)
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/Users/ericreis/go/1.15.15/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:194 +0x1cd
```

However I cannot return anything from my custom `StackTraceHandler` function and, therefore, I cannot get this information in my error handling middleware, that is where I'll send my error logs to Splunk.

Is there any way to do that? Am I missing something? 

**Code snippet** _Optional_
n/a

**Comment by ReneWerner87** [comment]
@ericreis am not quite sure how to help yet,
can you please create a small executable example for visualization and research

**Comment by efectn** [comment]
@ericreis

**Comment by ericreis** [comment]
Sorry for the delay guys, I was totally overwhelmed with other priorities. Here is the example:

```go
package main

import (
	"fmt"
	"runtime/debug"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/recover"
)

func errorHandling(c *fiber.Ctx) error {
	err := c.Next()
	fmt.Printf("handled error: %s\nstacktrace: %s\n\n", err, debug.Stack())
	return err
}

func main() {
	app := fiber.New()

	app.Use(errorHandling)
	app.Use(recover.New())
	app.Get("/", func(c *fiber.Ctx) error {
		panic("test")
		return c.SendString("Hello, World 👋!")
	})

	app.Listen(":3000")
}
```

And here the log that is printed when calling the API:

```
➜  fiber-panic-stacktrace go run main.go

 ┌───────────────────────────────────────────────────┐ 
 │                   Fiber v2.32.0                   │ 
 │               http://127.0.0.1:3000               │ 
 │       (bound on host 0.0.0.0 and port 3000)       │ 
 │                                                   │ 
 │ Handlers ............. 4  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ............. 64068 │ 
 └───────────────────────────────────────────────────┘ 

handled error: test
stacktrace: goroutine 36 [running]:
runtime/debug.Stack()
        /Users/ericreis/.goenv/versions/1.18.0/src/runtime/debug/stack.go:24 +0x65
main.errorHandling(0x12cb300?)
        /Users/ericreis/dev/study/fiber-panic-stacktrace/main.go:13 +0x2c
github.com/gofiber/fiber/v2.(*App).next(0xc0001d2000, 0xc00015a840)
        /Users/ericreis/go/1.18.0/pkg/mod/github.com/gofiber/fiber/v2@v2.32.0/router.go:132 +0x1be
github.com/gofiber/fiber/v2.(*App).handler(0xc0001d2000, 0x109e6f7?)
        /Users/ericreis/go/1.18.0/pkg/mod/github.com/gofiber/fiber/v2@v2.32.0/router.go:159 +0x45
github.com/valyala/fasthttp.(*Server).serveConn(0xc0001546c0, {0x1395038?, 0xc000124140})
        /Users/ericreis/go/1.18.0/pkg/mod/github.com/valyala/fasthttp@v1.35.0/server.go:2338 +0x1268
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00012ac80, 0xc000146300)
        /Users/ericreis/go/1.18.0/pkg/mod/github.com/valyala/fasthttp@v1.35.0/workerpool.go:224 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        /Users/ericreis/go/1.18.0/pkg/mod/github.com/valyala/fasthttp@v1.35.0/workerpool.go:196 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /Users/ericreis/go/1.18.0/pkg/mod/github.com/valyala/fasthttp@v1.35.0/workerpool.go:195 +0x1b0
```

As it can be seen, the stacktrace does not refer to the `panic`. How can I achieve that? I already tried with a custom recover handler, but have not been successful with it.

**Comment by Trim21** [comment]
the traceback will be the err if the handle panic and panic value is not an error.
