### ISSUE TITLE
🐛 panic: workerpool index out of range 

### ISSUE THREAD

**Issue by grishy** [gofiber/fiber#1902]
**Fiber version**
Fiber v2.30.0 

**Issue description**
Hi, I was making a plug and decided to test it with **k6**. I attach the code of the application and the script for testing. While running, the application ended up panicking.

**Code snippet**

```go
package main

import (
	"fmt"
	"os"
	"strconv"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"

	"api/device"
)

func serve(verbose bool) {
	app := fiber.New()

	app.Get("/device/:id", func(c *fiber.Ctx) error {
		idStr := c.Params("id")
		id, err := strconv.Atoi(idStr)
		if err != nil {
			return err
		}

		d := devs[id]
		return c.JSON(d.Status())
	})

	app.Listen(":3000")
}

func main() {
	serve(false)
}

```
**k6**

```js
import http from "k6/http";
import { check } from "k6";

export const options = {
  stages: [
    { target: 1000, duration: "2s" },
    { target: 1000, duration: "20s" },
  ],
};

export default function () {
  const result = http.get("http://localhost:3000/device/10");
  check(result, {
    "http response status code is 200": result.status === 200,
  });
}

```
**output**

```shell
 ┌───────────────────────────────────────────────────┐ 
 │                   Fiber v2.30.0                   │ 
 │               http://127.0.0.1:3000               │ 
 │       (bound on host 0.0.0.0 and port 3000)       │ 
 │                                                   │ 
 │ Handlers ............. 4  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ............. 29216 │ 
 └───────────────────────────────────────────────────┘ 

panic: runtime error: index out of range [-2]

goroutine 855 [running]:
math/rand.(*rngSource).Uint64(...)
        /usr/local/opt/go/libexec/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0xc000150460?)
        /usr/local/opt/go/libexec/src/math/rand/rng.go:234 +0x9f
math/rand.(*Rand).Int63(...)
        /usr/local/opt/go/libexec/src/math/rand/rand.go:84
math/rand.(*Rand).Float64(...)
        /usr/local/opt/go/libexec/src/math/rand/rand.go:195
api/device.(*Device).Status(0xc000164600)
        /Users/grishy/projects/grishy/ms/services/mock/device/device.go:38 +0xc4
main.serve.func2(0xc000162b00)
        /Users/grishy/projects/grishy/ms/services/mock/main.go:52 +0x133
github.com/gofiber/fiber/v2.(*App).next(0xc0001f8000, 0xc000162b00)
        /Users/grishy/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/router.go:132 +0x1d8
github.com/gofiber/fiber/v2.(*App).handler(0xc0001f8000, 0x109bd57?)
        /Users/grishy/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/router.go:160 +0x45
github.com/valyala/fasthttp.(*Server).serveConn(0xc00015c6c0, {0x1458cb8?, 0xc000a3c1a8})
        /Users/grishy/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x12c8
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000134280, 0xc000b0a720)
        /Users/grishy/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        /Users/grishy/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /Users/grishy/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:195 +0x1b0

```

**Comment by grishy** [comment]
This also happens on Fiber v2.32.0

**Comment by grishy** [comment]
I didn't notice my code in the callstack. The problem is on my side :)
