### ISSUE TITLE
🤗 [Question]:  evictCount relate by fiber or fasthttp?

### ISSUE THREAD

**Issue by ben-swit** [gofiber/fiber#2067]
### Question Description

i writen here https://github.com/valyala/fasthttp/issues/1368

is relate by fiber?? 

when i remove fiber and convert gin  then not rise this issue 

if any relate fiber??

### Code Snippet (optional)

```go
panic: id (22) <= evictCount (87)

goroutine 338 [running]:
golang.org/x/net/http2/hpack.(*headerFieldTable).idToIndex(0xc0004cac80, 0xc0009731d0?)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/tables.go:119 +0xce
golang.org/x/net/http2/hpack.(*headerFieldTable).search(0xc0004cac80, {{0xc00107f460, 0xc}, {0xc0013511a0, 0x24}, 0x0})
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/tables.go:106 +0xe5
golang.org/x/net/http2/hpack.(*Encoder).searchTable(0xc0004cac80, {{0xc00107f460, 0xc}, {0xc0013511a0, 0x24}, 0x0})
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/encode.go:97 +0x88
golang.org/x/net/http2/hpack.(*Encoder).WriteField(0xc0004cac80, {{0xc00107f460, 0xc}, {0xc0013511a0, 0x24}, 0x0})
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/encode.go:62 +0x14a
google.golang.org/grpc/internal/transport.(*loopyWriter).writeHeader(0xc0004c9200, 0xfd, 0x0, {0xc000a0b440?, 0x8, 0xc0003e3e68?}, 0x424207?)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:684 +0x32a
google.golang.org/grpc/internal/transport.(*loopyWriter).originateStream(0xc0004c9200, 0xc000592100)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:671 +0x185
google.golang.org/grpc/internal/transport.(*loopyWriter).headerHandler(0xc0004c9200, 0xc00117fa90)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:659 +0x394
google.golang.org/grpc/internal/transport.(*loopyWriter).handle(0xc000481360?, {0x1375980?, 0xc00117fa90?})
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:831 +0x3e5
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0004c9200)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:539 +0x9e
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/http2_client.go:415 +0x65
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/http2_client.go:413 +0x1eb1
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
very hard to assess without seeing a piece of code or knowing what you are doing

can you provide a small example running locally that causes this error

please keep it as small as possible and don't include any security or other information in it

**Comment by ben-swit** [comment]
write some code 
```
app := fiber.New(fiber.Config{
		ServerHeader:  "Swit File",
		AppName:       "swit file server",
		StrictRouting: true,
		BodyLimit:     1024 * 1024 * 1024,
	})

	app.Use(func(ctx *fiber.Ctx) error {
		swithttp.SetXSwitLocationHeaderWithFiber(ctx)
		return ctx.Next()
	})

	app.Get("/_healthz", func(ctx *fiber.Ctx) error {
		return ctx.SendStatus(200)
	})

	app.Get("/", func(ctx *fiber.Ctx) error {
		return ctx.SendStatus(200)
	})

	app.Use(
		logger.New(logger.Config{
			Next: func(c *fiber.Ctx) bool {
				return c.Path() == "/"
			},
			Format:       "[${time}] ${status} - ${latency} ${method} ${path}\n",
			TimeFormat:   "15:04:05",
			TimeZone:     "Local",
			TimeInterval: 500 * time.Millisecond,
			Output:       os.Stdout,
		}),
		middlewares.RegionProxy(),
		cors.New(cors.Config{
			AllowOrigins:  "*",
			AllowMethods:  "POST, GET, OPTIONS, PUT, DELETE, UPDATE",
			AllowHeaders:  "Origin, Accept, Content-Type, Content-Length, X-Requested-With, x_access_token, Content-Disposition , xsoc, xmob,x_cmp_id, authorization, sentry-trace",
			ExposeHeaders: "",
		}),
		recover.New(func() recover.Config {
			c := recover.ConfigDefault
			c.EnableStackTrace = true
			return c
		}()),
		requestid.New(requestid.Config{
			Header: "X-Request-Id",
			Generator: func() string {
				return uuid.NewV4().String()
			},
			ContextKey: "X-Request-Id",
		}),
		func(ctx *fiber.Ctx) error {
			if ctx.Path() != "/" {
				return logger.New()(ctx)
			}
			return ctx.Next()
		},
	)
```

```

func (r Router) Download(ctx *fiber.Ctx) error {
	download, err := strconv.ParseBool(ctx.Query("download", "false"))
	if err != nil {
		return fu.Fail(ctx, http.StatusBadRequest, response.INVALID_PARAMETER, fmt.Errorf("must set download: %w", err))
	}

	ext := ctx.Query("ext", "none")

	meta, err := r.cs.Metadata(ctx.Context(), string(ctx.Context().Request.URI().Path()))
	if err != nil {
		fmt.Println("this error")
		return fu.Fail(ctx, fiber.StatusNotFound, response.ERROR, fmt.Errorf("google cloud storage attribute: %w", err))
	}

	fname := ctx.Query("file_name")
	if fname == "" {
		fname = filepath.Base(ctx.Path())
		t := transform.Chain(norm.NFD, runes.Remove(runes.In(unicode.Mn)), norm.NFC)
		fname, _, _ = transform.String(t, fname)
	}

	if !download {
		if ext != "none" {
			ctx.Set(fiber.HeaderContentType, policy.MimeTypeFilter(ext))
		} else {
			ctx.Set(fiber.HeaderContentType, policy.MimeTypeFilter(meta.ContentType))
		}
	} else {
		ctx.Set(fiber.HeaderContentType, "application/octet-stream; charset=utf-8")
		ctx.Set(fiber.HeaderContentDisposition, "attachment; filename*=UTF-8''"+url.PathEscape(fname))
	}

	ctx.Set(fiber.HeaderContentLanguage, meta.ContentLanguage)
	ctx.Set(fiber.HeaderContentEncoding, meta.ContentEncoding)
	ctx.Set(fiber.HeaderVary, "Accept-Encoding")
	ctx.Set(fiber.HeaderCacheControl, "public, max-age=86400")

	var start int
	var end = -1
	// Response Range data

	if rn, err := ctx.Range(int(meta.Size)); err == nil && len(rn.Ranges) > 0 {
		ctx.Status(fiber.StatusPartialContent)
		ctx.Set(fiber.HeaderAcceptRanges, "bytes")
		switch {
		case rn.Ranges[0].End == 0:
			end = int(meta.Size) - 1
		default:
			end = rn.Ranges[0].End
		}
		ctx.Set(fiber.HeaderContentRange, fmt.Sprintf("bytes %d-%d/%d", rn.Ranges[0].Start, end, meta.Size))
		start = rn.Ranges[0].Start
	}

	reader, err := r.cs.GetFile(ctx.Context(), string(ctx.Context().Request.URI().Path()), int64(start), int64(end))
	if err != nil {
		return fu.Fail(ctx, fiber.StatusNotFound, response.ERROR, fmt.Errorf("download error: %w", err))
	}
	defer reader.Close()
	if err := ctx.SendStream(reader); err != nil {
		return err
	}
	if download {
		if v, ok := ctx.Locals("user").(*auth_v4.UserToken); ok {
			r.publishAuditLog(ctx, fiber.StatusOK, v.GetCmpId(), v.GetUserId(), v.GetUserEmail(), fname)
		}
	}
	return nil
}
```

this is small sample when i do stress test  1min 200 count  then after a few seconds rise this 

and i want to know fiber is fast but is it fit file server?? 

in my case fiber use file server i know fasthttp use bytes bufferpool  but so many use memory over 4GB

**Comment by ben-swit** [comment]
[sample.log](https://github.com/gofiber/fiber/files/9460197/sample.log)

 this is my full trace debug

**Comment by efectn** [comment]
> [sample.log](https://github.com/gofiber/fiber/files/9460197/sample.log)
> 
> this is my full trace debug

It's probably related to grpc library, not Fiber

**Comment by ben-swit** [comment]
but when i convert fiber to gin not happen this panic  

is not relate fiber? or fasthttp?

**Comment by efectn** [comment]
Please share full code as repository. I can't see anything related to Fiber in panic message.

**Comment by ben-swit** [comment]
sorry @efectn  repo is private repo but i solved remove fiber so close issue

**Comment by ReneWerner87** [comment]
@ben-swit what was the cause that others who find the error there may also have a clue

**Comment by ben-swit** [comment]
@ReneWerner87 i don't know specifically, i solved change fiber to gin

**Comment by gaby** [comment]
@ReneWerner87 This was caused because gprc defaults to using HTTP/2 which is not supported by fasthttp/fiber. The solution is to disable the http2 transport. Fix is here: https://github.com/golang/go/issues/43051#issuecomment-878092933

**Comment by ReneWerner87** [comment]
Ok thx

**Comment by vinkent420** [comment]
Hi @ReneWerner87 , I fully hopefull this issue was be fix in Fiber (sr if I miss if it was be fixed). I dont want by this issue lead to using another framework really

**Comment by vinkent420** [comment]
Thank @ReneWerner87 a lots. My team is doubling check and if still cannot fix, we will share snippet soon. Thank @ReneWerner87 again 👍

**Comment by HelloHaiGG** [comment]
Is there a proper solution to this problem, I am also encountering this problem

**Comment by 0x113** [comment]
Same here. We tried fiber for the first time, and we love it so far. Unfortunately, we ran into the same panic.

**Comment by 0x113** [comment]
@ReneWerner87, thank you for your response. As you mentioned, the reference to Fiber data was the problem. At least in our case. 

We've been passing `c.UserContext()` to one of the methods that generate a context for gRPC requests. We decided to set the `Immutable` value to `true` for the config, and it resolved the issue as mentioned in the documentation.

**Comment by ReneWerner87** [comment]
Ok, then you had previously used something that was a reference
![image](https://github.com/gofiber/fiber/assets/7063188/bad5968b-2a55-42b5-8811-9a9ec4255a07)

because the immutable switch only changes this behavior

**Comment by ReneWerner87** [comment]
ok

**Comment by xuxiao415** [comment]
When using HTTP/2, if the underlying byte slice of the header value string set is modified elsewhere, it may lead to duplicate data in the dynamic table. As a result, unexpected data might be evicted from the dynamic table, potentially causing exceptions when searching within the dynamic table.It would be best to check if `sync.Pool` is used in the code.
