### ISSUE TITLE
🐛 Logger does not set default values

### ISSUE THREAD

**Issue by mrchypark** [gofiber/fiber#526]
**Fiber version**
github.com/gofiber/fiber v1.12.1

**Issue description**
I want to log with out statecode 200. 
So I add Next options to logger using ctx.Fasthttp.Response.StatusCode() and get panic.

**Code snippet**

```go
package main

import (
	"github.com/gofiber/fiber"
	"github.com/gofiber/fiber/middleware"
)

func main() {
	app := fiber.New()
	app.Use(middleware.LoggerWithConfig(middleware.LoggerConfig{
		Next: func(ctx *fiber.Ctx) bool {
			return ctx.Fasthttp.Response.StatusCode() != 200
		},
		Format:     "${time} feph ${method} ${path} - ${status} - ${latency}\nRequest : ${body}\n",
		TimeFormat: "2006-01-02T15:04:05-0700",
	}))
	app.Get("/", hello)
	app.Listen(3000)
}

func hello(c *fiber.Ctx) {
	c.Send("Hello, World 👋!")
}
```

**Panic message**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x822f1b]

goroutine 23 [running]:
github.com/gofiber/fiber/middleware.LoggerWithConfig.func2(0xc00059a100)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.1/middleware/logger.go:201 +0x21b
github.com/gofiber/fiber.(*App).next(0xc00006a060, 0xc00059a100, 0xc00059a100)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.1/router.go:109 +0x1c2
github.com/gofiber/fiber.(*App).handler(0xc00006a060, 0xc000140500)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.1/router.go:125 +0x64
github.com/valyala/fasthttp.(*Server).serveConn(0xc000598000, 0x9a57e0, 0xc000010078, 0x0, 0x0)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.14.0/server.go:2162 +0x11bb
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000124280, 0xc00000e040)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.14.0/workerpool.go:223 +0xc0
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc000124280, 0xc00000e040, 0x84e980, 0xc00000e040)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.14.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /go/pkg/mod/github.com/valyala/fasthttp@v1.14.0/workerpool.go:194 +0x101
exit status 2
```

**Comment by mrchypark** [comment]
example accure same panic

```go
package main

import (
	"github.com/gofiber/fiber"
	"github.com/gofiber/fiber/middleware"
)

func main() {
	app := fiber.New()

	// Default
	app.Use(middleware.Logger())

	// Custom logging format
	app.Use(middleware.Logger("${method} - ${path}"))

	// Custom Config
	app.Use(middleware.LoggerWithConfig(middleware.LoggerConfig{
		Next: func(ctx *fiber.Ctx) bool {
			return ctx.Path() != "/private"
		},
		Format: "${method} - ${path}",
	}))

	app.Listen(4000)
}

```

```
GET http://localhost:4000/private
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8231cb]

goroutine 37 [running]:
github.com/gofiber/fiber/middleware.LoggerWithConfig.func2(0xc000528000)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.2/middleware/logger.go:201 +0x21b
github.com/gofiber/fiber.(*App).next(0xc000102480, 0xc000528000, 0xaa26c3a5046)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.2/router.go:107 +0x176
github.com/gofiber/fiber.(*Ctx).Next(0xc000528000, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.2/ctx.go:619 +0x138
github.com/gofiber/fiber/middleware.LoggerWithConfig.func2(0xc000528000)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.2/middleware/logger.go:139 +0xbd
github.com/gofiber/fiber.(*App).next(0xc000102480, 0xc000528000, 0xaa26c3a4e52)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.2/router.go:107 +0x176
github.com/gofiber/fiber.(*Ctx).Next(0xc000528000, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.2/ctx.go:619 +0x138
github.com/gofiber/fiber/middleware.LoggerWithConfig.func2(0xc000528000)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.2/middleware/logger.go:139 +0xbd
github.com/gofiber/fiber.(*App).next(0xc000102480, 0xc000528000, 0xc000528000)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.2/router.go:107 +0x176
github.com/gofiber/fiber.(*App).handler(0xc000102480, 0xc000520000)
        /go/pkg/mod/github.com/gofiber/fiber@v1.12.2/router.go:123 +0x64
github.com/valyala/fasthttp.(*Server).serveConn(0xc00010e6c0, 0x9a5660, 0xc000010030, 0x0, 0x0)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.14.0/server.go:2162 +0x11bb
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00007ed20, 0xc00000e040)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.14.0/workerpool.go:223 +0xc0
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc00007ed20, 0xc00000e040, 0x84e980, 0xc00000e040)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.14.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /go/pkg/mod/github.com/valyala/fasthttp@v1.14.0/workerpool.go:194 +0x101
exit status 2
```

**Comment by kiyonlin** [comment]
You forget to provide Output in the config :smile:

**Comment by mrchypark** [comment]
@kiyonlin but when I try add `Output:     os.Stderr,` line, and not accure panic. 

Thank you for your advice :)

**Comment by kiyonlin** [comment]
@mrchypark I recommend you to use https://github.com/gofiber/logger instead.

**Comment by mrchypark** [comment]
@kiyonlin This https://github.com/gofiber/logger is not support when log print or not. (sad)

**Comment by kiyonlin** [comment]
@mrchypark Filter option is the same as Next

**Comment by mrchypark** [comment]
@kiyonlin How do I add with logger options?

**Comment by kiyonlin** [comment]
@mrchypark Sorry, I didn’t notice that the repo is no longer maintained.

**Comment by mrchypark** [comment]
@kiyonlin I know about Output: os.Stderr, line becouse of you. Thank you again :)

**Comment by kiyonlin** [comment]
@mrchypark you’re welcome :smile:

**Comment by Fenny** [comment]
@mrchypark, `v1.12.3` contains an improved logger structure ( default config included ), see [logger readme](https://github.com/gofiber/fiber/blob/master/middleware/logger.md)
```go
import (
  "github.com/gofiber/fiber"
  "github.com/gofiber/fiber/middleware"
)

func main() {
  // ...

  // Default Logger
  app.Use(middleware.Logger())

  // Pass a custom output
  app.Use(middleware.Logger(os.Stdout))

  // Pass a custom timeformat
  app.Use(middleware.Logger("15:04:05"))

  // Pass a custom format
  app.Use(middleware.Logger("${time} ${method} ${path}"))

  // Pass a custom  output + timeformat + format
  app.Use(middleware.Logger(os.Stdout, "15:04:05", "${time} ${method} ${path}"))

  // Order does not matter
  app.Use(middleware.Logger("${time} ${method} ${path}", os.Stdout, "15:04:05"))

  // Pass a custom config
  app.Use(middleware.Logger(middleware.LoggerConfig{
      Format:     "${time} ${method} ${path}",
      TimeFormat: "15:04:05",
      Output:     os.Stdout,
  }))

  // ...
}
```

**Comment by mrchypark** [comment]
Amazing work!
