### ISSUE TITLE
🤔 How to use the session mw?

### ISSUE THREAD

**Issue by xjester0** [gofiber/fiber#685]
**Fiber version**
1.12.7

**Issue description**
Tests crash server

```
cmd go-wrk-master.exe http://127.0.0.1:3000/
Running 10s test @ http://127.0.0.1:3000/
  10 goroutine(s) running concurrently

360 requests in 15.10335ms, 94.22KB read
Requests/sec:           23835.77
Transfer/sec:           6.09MB
Avg Req Time:           419.537µs
Fastest Request:        0s
Slowest Request:        5.0011ms
Number of Errors:       20
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x4598b1]

goroutine 22 [running]:
github.com/savsgio/dictpool.appendArgs(...)
        C:/[...]/go/src/github.com/savsgio/dictpool/dict.go:46
github.com/savsgio/dictpool.setArgs(0xc0003d8000, 0x126, 0x220, 0xc0003b4ed0, 0x24, 0x874a60, 0xc00031b1d0, 0xc0002df9e0, 0x46157d, 0x874a60)
        C:/[...]/go/src/github.com/savsgio/dictpool/dict.go:77 +0x198
github.com/savsgio/dictpool.(*Dict).SetBytes(0xc0002f8020, 0xc0003b4ed0, 0x24, 0x24, 0x874a60, 0xc00031b1d0)
        C:/[...]/go/src/github.com/savsgio/dictpool/dict.go:134 +0xea
github.com/fasthttp/session/providers/memory.(*Provider).Save(0xc0002fc008, 0xc0003b4ed0, 0x24, 0x24, 0xd88fb0, 0x0, 0x0, 0x274a48a78000, 0xc00002a500, 0x19c06b0)
        C:/[...]/go/src/github.com/fasthttp/session/providers/memory/provider.go:57 +0x12a
github.com/fasthttp/session.(*Session).Save(0xc0003000c0, 0xc0002e8a00, 0xc0002fa400, 0xc00032e000, 0xc0002dfaf0)
        C:/[...]/go/src/github.com/fasthttp/session/session.go:198 +0x162
github.com/gofiber/session.(*Store).Save(0xc0002ed3a0, 0x0, 0x0)
        C:/[...]/go/src/github.com/gofiber/session/store.go:27 +0x56
main.Session.func1(0xc00031e090)
        C:/GoProd/iss/main.go:27 +0x13d
github.com/gofiber/fiber.(*App).next(0xc000310000, 0xc00031e090, 0xc00031e090)
        C:/[...]/go/src/github.com/gofiber/fiber/router.go:112 +0x182
github.com/gofiber/fiber.(*App).handler(0xc000310000, 0xc0002e8a00)
        C:/[...]/go/src/github.com/gofiber/fiber/router.go:136 +0x6b
github.com/valyala/fasthttp.(*Server).serveConn(0xc000314000, 0x9d11c0, 0xc000006030, 0x0, 0x0)
        C:/[...]/go/src/github.com/valyala/fasthttp/server.go:2162 +0x10e8
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000132090, 0xc0002ec800)
        C:/[...]/go/src/github.com/valyala/fasthttp/workerpool.go:223 +0xc7
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc000132090, 0xc0002ec800, 0x875920, 0xc0002ec800)
        C:/[...]/go/src/github.com/valyala/fasthttp/workerpool.go:195 +0x3c
created by github.com/valyala/fasthttp.(*workerPool).getCh
        C:/[...]/go/src/github.com/valyala/fasthttp/workerpool.go:194 +0x117
```

**Code snippet**

```go
package main

import (
	"github.com/gofiber/fiber"
	"github.com/gofiber/session"
	"time"
)

func main() {
	store := session.New(session.Config{
		GCInterval: 5 * time.Minute,
	})

	app := fiber.New()
	app.Use(Session(store))
	app.Get("/", Handler())

	panic(app.Listen(3000))
}

func Session(sessions *session.Session) func(*fiber.Ctx) {
	return func(c *fiber.Ctx) {
		store := sessions.Get(c)
		defer store.Save()
		c.Locals("session", store)
		c.Next()
	}
}

func Handler() func(*fiber.Ctx) {
	return func(c *fiber.Ctx) {
		sess := c.Locals("session").(*session.Store)
		c.Status(200).SendString(sess.ID())
	}
}
```

**Comment by Fenny** [comment]
```go
// package main

// import (
// 	"fmt"
// 	"time"

// 	"github.com/gofiber/fiber"
// )

// var helloWorld = []byte("Hello, World!")

// // external
// func demo1() {
// 	app := fiber.New()

// 	secureCookies := middleware.SecureCookies("badsecret") // secret

// 	app.Get("/get", func(c *fiber.Ctx) {
// 		// user=CP7AWaXDfAKIRfH49dQzKJx7sKzzSoPq7/AcBBRVwlI3
// 		user, err := secureCookies.Get(c, "user")
// 		fmt.Println(user, err) // john, nil
// 	})

// 	app.Get("/set", func(c *fiber.Ctx) {
// 		// Create cookie
// 		cookie := new(fiber.Cookie)
// 		cookie.Name = "john"
// 		cookie.Value = "doe"
// 		cookie.Expires = time.Now().Add(24 * time.Hour)

// 		// Set signed cookie
// 		err := secureCookies.Set(c, "user", "john")
// 	})
// }

// // internal
// func demo1() {
// 	app := fiber.New(&fiber.Settings{
// 		CookieSecret: "badsecret",
// 	})

// 	app.Get("/get", func(c *fiber.Ctx) {
// 		// user=CP7AWaXDfAKIRfH49dQzKJx7sKzzSoPq7/AcBBRVwlI3
// 		user, err := c.SignedCookies("user")
// 		fmt.Println(user, err) // john, nil
// 	})
// 	app.Get("/set", func(c *fiber.Ctx) {
// 		// Create cookie
// 		cookie := new(fiber.Cookie)
// 		cookie.Name = "john"
// 		cookie.Value = "doe"
// 		cookie.Expires = time.Now().Add(24 * time.Hour)

// 		// Set signed cookie
// 		err := c.SignedCookie("user", cookie)
// 	})
// }

package main

import (
	"log"
	"time"

	"github.com/gofiber/fiber"
	"github.com/gofiber/session"
)

// create session handler
var sessions = session.New(session.Config{
	GCInterval: 5 * time.Minute,
})

func main() {
	app := fiber.New()

	app.Use(Session())
	app.Get("/", Handler())

	log.Fatal(app.Listen(3000))
}

func Session() func(*fiber.Ctx) {
	return func(c *fiber.Ctx) {
		store := sessions.Get(c)
		defer store.Save()
		c.Next()
	}
}

func Handler() func(*fiber.Ctx) {
	return func(c *fiber.Ctx) {
		store := sessions.Get(c)
		c.SendString(store.ID())
	}
}
```

**Comment by xjester0** [comment]
Use this code, updated fiber and session, but problem not solved

**Comment by Fenny** [comment]
Everything seems to work on my end, could you double-check your `go.mod` & `go.sum` are up-to-date by using `go get -u` && `go mod tidy`. And could you share any errors you are getting?

**Comment by thomasvvugt** [comment]
Could be related to https://github.com/gofiber/session/issues/8
